language: ruby
rvm:
  - 2.4.2

branches:
  only:
    - source

cache: bundler
git:
  depth: false
script:
  - bundle exec jekyll build --destination _site
#  - bundle exec htmlproofer --checks-to-ignore "ImageCheck" --url-ignore '/^((?!github\.com\/.*\/wiki\/).)*$/' ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: _site
  on:
    branch: source
  target-branch: master

sudo: false
